### ISSUE TITLE
OccupancySetpoint is mis-spelt

### ISSUE THREAD

**Issue by akshayj-MSFT** [WillowInc/opendigitaltwins-building#1]
[Occupancy Setpoint](https://github.com/WillowInc/opendigitaltwins-building/blob/main/Ontology/Willow/Capability/Parameter/Setpoint/OccupancySetpoint/OccupancySetpiont.json) interface filename has a typo.

It should be OccupancySetpoint, not OccupancySetpiont.json

![image](https://user-images.githubusercontent.com/2495924/104250213-f3733600-5421-11eb-8274-14eeb5321263.png)
@rszcodronski

**Comment by rszcodronski** [comment]
Fixed filename typo in #2 pull request and merged to main branch.
