### ISSUE TITLE
Why should relationships be defined on the "children" twins

### ISSUE THREAD

**Issue by hannesstockner** [WillowInc/opendigitaltwins-building#96]
Hi,

first of all thanks a lot for this repo and all the information you provide online about your approach.
Your work is very inspiring.

[Here](https://github.com/WillowInc/opendigitaltwins-building#frequency-asked-questions) you mention that relationships should be defined on the "children" twins.

What are the reasons behind this recommendation?

Thanks a lot.
Hannes

**Comment by joebeernink** [comment]
Closing due to change of processes.
